{{- if ne .Values.service.type "Ingress" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-flask-app.fullname" . }}-service
  labels:
    app: {{ include "simple-flask-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "simple-flask-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
