# This workflow builds the SUT Docker image and pushes it to GitHub Container Registry
# It triggers on push to main/master or on manual dispatch

name: Build and Push Test backend Container Image

on:
  push:
    branches: [ master, main ]
    paths:
      - 'simple-flask/**'
      - '.github/workflows/build-simple-flask.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Python for testing
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run build and test script
        run: |
          (cd simple-flask && sh ./test_app.sh )

      # - name: Install dependencies for testing
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flask

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Read BUILDDATE
      #   id: builddate
      #   run: echo "date=$(cat BUILDDATE.DAT)" >> $GITHUB_OUTPUT

      - name: Build and push SUT image
        uses: docker/build-push-action@v5
        with:
          context: ./simple-flask/
          #file: ./Containerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/simple-flask:latest

# ghcr.io/${{ github.repository }}/webrouter-base:${{ steps.builddate.outputs.date}}
